<?
if(!CSite::InGroup(array(1,11,12)))die('Нет доступа.');
$ed=true;
$arResult=Aiplk::getUser($userId);
//$curUser=Aiplk::getUser($GLOBALS['USER']->getID());
?>
<form action="" id="l_profile_edit">

  <input type="hidden" name="ID" value="<?=$userId?>">
  <input type="hidden" name="no_change_groups" value="Y">

                    <div class="wrap-input100 form-outline mb-2">
                        <span class="label-input">Фамилия:<span class="starrequired">*</span></span>
                        <input required class="form-control form-control-lg" type="text" name="user[LAST_NAME]" maxlength="50" value="<?= $arResult["LAST_NAME"] ?>"/>
                    </div>                 
                    <div class="wrap-input100 form-outline mb-2">
                        <span class="label-input">Имя:<span class="starrequired">*</span></span>
                        <input required class="form-control form-control-lg" type="text" name="user[NAME]" maxlength="50" value="<?= $arResult["NAME"] ?>"/>
                    </div>
                    <div class="wrap-input100 form-outline mb-2">
                        <span class="label-input">Отчество:<span class="starrequired">*</span></span>
                        <input required class="form-control form-control-lg" type="text" name="user[SECOND_NAME]" maxlength="50" value="<?= $arResult["SECOND_NAME"] ?>"/>
                    </div>                    

                    <div class="wrap-input100 form-outline mb-2 aip_line">
                        <span class="label-input">Дата рождения:</span>
                        <input required class="form-control form-control-lg" type="date" name="user[PERSONAL_BIRTHDAY]" maxlength="50" value="<?=ConvertDateTime($arResult['PERSONAL_BIRTHDAY'], "YYYY-MM-DD", "ru")?>"/>
                    </div>

<div class="wrap-input100 form-outline mb-2">
          <span class="label-input">Телефон<span class="req">*</span></span> 
          <input <?=((!$ed)?'disabled':'')?> required class="form-control form-control-lg" type="text" name="user[PERSONAL_PHONE]" maxlength="50" value="<?php echo $arResult["PERSONAL_PHONE"] ?>"/>
</div>
<div class="wrap-input100 form-outline mb-2">
          <span class="label-input">Почта<span class="req">*</span></span> 
          <input <?=((!$ed)?'disabled':'')?> required class="form-control form-control-lg" type="text" name="user[EMAIL]" maxlength="50" value="<?php echo $arResult["EMAIL"]?>"/>
</div>

<div class="wrap-input100 form-outline mb-2 aip_line">
    <span class="label-input">Тренер</span>
    <select <?=((!$ed)?'disabled':'')?> style="width:auto;max-width: 100%;" class="form-control form-control-lg form-control form-control-lg-lg inp_tags_trener" data-f="UF_TRENER_ID" name="user[UF_TRENER_ID]">
                      <option value="<?=$arResult["UF_TRENER_ID"]?>"><?=Aiplk::getFIO($arResult["UF_TRENER_ID"])?></option>
                      <?/*foreach(Aiplk::getUserSportsmeny(null, 10, false) as $row){?>
                        <option <?=(($arResult["UF_TRENER_ID"]==$row['ID'])?'selected':'')?> value="<?=$row['ID']?>"><?=Aiplk::getFIO($row)?></option>
                      <?}*/?>                              
    </select>
</div>  

<div class="wrap-input100 form-outline mb-2 aip_line">
    <span class="label-input">Регион</span>
    <select <?=((!$ed)?'disabled':'')?> style="width:auto;max-width: 100%;" class="form-control form-control-lg form-control form-control-lg-lg inp_tags" name="user[UF_REGION]" id="PERSONAL_STATE">
                        <?$aRegion=Aiplk::getRegionTitle($arResult)?>
                        <option selected value="<?=$aRegion['xmlval']?>"><?=$aRegion['txt']?></option>
  </select>
</div> 

<div class="wrap-input100 form-outline mb-2 aip_line">
    <span class="label-input">Спортивный разряд/звание</span>                                 
    <select class="form-control form-control-lg form-control form-control-lg-lg" id="UF_RAZR" name="user[UF_RAZR]">
        <option value="">Не выбрано</option>
				<?foreach(Aiplk::getRazryad() as $row){?>
					<option <?=(($arResult["UF_RAZR"]==$row['ID'])?'selected':'')?> value="<?=$row['ID']?>"><?=$row['NAME']?></option>
        <?}?>
		</select>             
</div>
        
<div class="wrap-input100 form-outline mb-2">
  <span class="label-input">Комментарий</span> 
  <textarea <?=((!$ed)?'disabled':'')?> class="form-control form-control-lg" type="text" id="OBJECT_NAME" name="user[UF_COMM]"><?=$arResult['UF_COMM']?></textarea>
</div>

	<div class="wrap-input100 form-outline mb-2 aip_line">
      <span class="label-input">Судейская категория</span>                                 
      <select class="form-control form-control-lg form-control form-control-lg-lg" id="UF_SUD_KAT" name="user[UF_SUD_KAT]">
          <option value="">Не выбрано</option>
					<?foreach(Aiplk::getKategoriiSudi() as $row){?>
						<option <?=(($arResult["UF_SUD_KAT"]==$row['ID'])?'selected':'')?> value="<?=$row['ID']?>"><?=$row['NAME']?></option>
          <?}?>
			</select>             
	</div>	
  
  <div class="wrap-input100 form-outline mb-2 aip_line">
      <span class="label-input">Тренерская категория</span>                                 
      <select class="form-control form-control-lg form-control form-control-lg-lg" id="UF_TRENER_KAT" name="user[UF_TRENER_KAT]">
          <option value="">Не выбрано</option>
					<?foreach(Aiplk::getKategoriiSudi() as $row){?>
						<option <?=(($arResult["UF_TRENER_KAT"]==$row['ID'])?'selected':'')?> value="<?=$row['ID']?>"><?=$row['NAME']?></option>
          <?}?>
			</select>             
	</div>  
  
  <div class="wrap-input100 form-outline mb-2 aip_line">
      <span class="label-input">Тренер / лицензия Тип:</span>                                 
      <select class="form-control form-control-lg form-control form-control-lg-lg" id="UF_LIC_TRENER_TIP" name="user[UF_LIC_TRENER_TIP]">
          <option value="">Не выбрано</option>
					<?foreach(Aiplk::getEnumList('UF_LIC_TRENER_TIP') as $id=>$row){?>
						<option <?=(($arResult["UF_LIC_TRENER_TIP"]==$id)?'selected':'')?> value="<?=$id?>"><?=$row?></option>
          <?}?>
			</select>             
	</div>
  <div class="wrap-input100 form-outline mb-2">
      <span class="label-input">Тренер / лицензия Номер:</span>
      <input required class="form-control form-control-lg" type="text" name="user[UF_LIC_TRENER_NOMER]" maxlength="50" value="<?= $arResult["UF_LIC_TRENER_NOMER"] ?>"/>
  </div>   
  <div class="wrap-input100 form-outline mb-2 aip_line">
      <span class="label-input">Тренер / лицензия Срок действия:</span>
      <input required class="form-control form-control-lg" type="date" name="user[UF_LIC_TRENER_SROK]" maxlength="50" value="<?=ConvertDateTime($arResult['UF_LIC_TRENER_SROK'], "YYYY-MM-DD", "ru")?>"/>
  </div>




<div class="wrap-input100 mt-4 btn_cont_1">
  <?if($ed){?>
  <input id="l_profile_edit_btn" type="button" name="go" value="Сохранить" class="questionnaire_btn btn btn-primary">
  <?}?>
</div>
</form>

<script>
$('body').on('focus','.l_err',function(){$(this).removeClass('l_err')})
$('body').on('click','#l_profile_edit_btn',function(e){
  $('.overlay_loading').addClass('active');
  var formData = new FormData(document.forms.l_profile_edit);
  //console.log(formData);return false;
  $.ajax({
    type: 'POST',
    url: '<?=SITE_TEMPLATE_PATH ?>/ajax/profile_edit.php',
    data: formData,
    contentType: false,
    processData: false,
    dataType : "json",
    success:function(data) {
      if(data.err)console.log(data.err);
      else{
        //$('.overlay_loading').removeClass('active');
        window.location.reload();
      }
    }
  });
  e.preventDefault();
  return false; 
});

   //select2
  $('.inp_tags_trener').select2({
    'placeholder':'Не выбрано',
    'tags':false,
    'selectOnClose':false,
    'closeOnSelect':true,
    'ajax':{
      url: '/local/templates/lk/ajax/get_trener.php',
      dataType: 'json',
      delay: 250,
    }
  });    
  $('.inp_tags').select2({
    'tags':false,
    'selectOnClose':false,
    'closeOnSelect':true,
    'ajax':{
      url: '/local/templates/lk/ajax/get_gorod.php',
      dataType: 'json',
      delay: 250
    }
  }); 
</script>